---
title: "Auxillary tables"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  warning = FALSE,
  comment = "#>"
)
```

```{r}
library(fmr)
library(tidyverse)
key <- "your_FM_API_key"
```

```{r, echo = FALSE}
key <- Sys.getenv("fm_key")
```

## Preamble

This document is just to explore the FM data model, done to prevent any misunderstanding when setting up the downstream code.

## Site

```{r}
fmr:::fm_site(key, trim = FALSE) |> glimpse()
```

## Vessel

The vessel registry can be accessed in three ways:

```{r}
vf <- fm_vesselF(key)
vd <- fm_vesselD(key)
v  <- fm_vessel(key, add_owner = TRUE, add_operator = TRUE)
v |> glimpse()
```


### vesselF

```{r}
fmr:::fm_vesselF(key) |> glimpse()
```

### vesselD

```{r}
fmr:::fm_vesselD(key) |> glimpse()
```

## licence

### licenceF

```{r}
fmr:::fm_licenseF(key) |> glimpse()
```

### licenceV

```{r}
fmr:::fm_licenseV(key) |> glimpse()
```

## party


### partyV

```{r}
fmr:::fm_partyV(key) |> glimpse()
```

## choice

### choiceD

```{r}
fmr:::fm_choice(key) |> glimpse()
```

