utils::globalVariables(c("arr_location_id",
                         "arr_status_id",
                         "arr_time",
                         "condition_id",
                         "created_by",
                         "created_date",
                         "created_date_time_str",
                         "day",
                         "dep_location_id",
                         "dep_status_id",
                         "dep_time",
                         "disposition_id",
                         "first_name",
                         "fishing_zone_id",
                         "friendly_name",
                         "fuel",
                         "fuel_used",
                         "gear_id",
                         "hid1",
                         "hid2",
                         "id",
                         "infraction_desc",
                         "infraction_type_id",
                         "is_active",
                         "is_by_catch",
                         "is_targetted",
                         "island",
                         "landing_date",
                         "landing_date_time_str",
                         "landing_site_id",
                         "last_name",
                         "last_modified_date",
                         "lat",
                         "latitude",
                         "lon",
                         "longitude",
                         "measurement_type_id",
                         "month",
                         "party_id",
                         "operator_id",
                         "owner_id",
                         "price",
                         "quarter",
                         "reg",
                         "registration_date",
                         "registration_no",
                         "secondary_vessel_id",
                         "site",
                         "species",
                         "species_id",
                         "storage_id",
                         "survey",
                         "survey_date",
                         "survey_id",
                         "survey_item_dtl_id",
                         "survey_item_id",
                         "survey_item_status_id",
                         "survey_item_type_id",
                         "survey_period_from",
                         "survey_period_to",
                         "survey_start_time",
                         "survey_stop_time",
                         "survey_status_id",
                         "T1",
                         "T2",
                         "tenant_id",
                         "time",
                         "time vessel_id",
                         "total_boats",
                         "week",
                         "vessel_id",
                         "vessel_name",
                         "vid",
                         "vessel",
                         "vocabulary",
                         "weight",
                         "year",
                         ".s1",
                         ".s2",
                         ".cn",  ".ct",  ".un",  ".ut",
                         "area",
                         "batch_no",
                         "choice_id", "code", "collector", "column_name", "cooler_no",
                         "data_collector_id", "depth_max", "depth_min", "dump_pth",
                         "fishing_zone", 
                         "gear_size",
                         "item_count",
                         "last_modified_by", "location", "location_id", 
                         "measurement_type", "middle_name", 
                         "no_of_gears", "no_of_sets",
                         "operator", "owner", 
                         "site1", "site2", "soak_time", "status", "survey_type_id",
                         "table_name", "type",
                         "variable"))
